// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'eu-west-1:8f920f03-220f-4c0b-84f9-272fc70ff3e9',
aws_cognito_region : 'eu-west-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'digital-hosting-mobilehub-1242215993',
aws_content_delivery_bucket_region : 'eu-west-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd3zla3oujiywe.cloudfront.net',
aws_mobile_analytics_app_id : 'e60e0ba55f424be9824f1c04b6eb37b2',
aws_project_id : 'f53dafe1-3e77-4dec-9441-98c3bb784996',
aws_project_name : 'Digital',
aws_project_region : 'eu-west-1',
aws_resource_name_prefix : 'digital-mobilehub-1242215993',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});